(function(g){var window=this;var rpa=function(a,b){return g.Ub(a,b)},d4=function(){},spa=function(a){if(a.tc&&"function"==typeof a.tc)return a.tc();
if(g.v(a))return a.split("");if(g.Ka(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Qb(a)},tpa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Ka(a)||g.v(a))(0,g.B)(a,b,void 0);else{if(a.Fd&&"function"==typeof a.Fd)var c=a.Fd();else if(a.tc&&"function"==typeof a.tc)c=void 0;else if(g.Ka(a)||g.v(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Rb(a);d=spa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},e4=function(a){g.dn(a,"zx",g.rc());
return a},f4=function(a,b,c){g.Ja(c)||(c=[String(c)]);
g.jn(a.l,b,c)},g4=function(a){return(a=g.Ao(a))?new ActiveXObject(a):new XMLHttpRequest},h4=function(a,b){return b+" ["+a.ba+" "+a.F+" "+a.getStatus()+"]"},upa=function(a){return"content-type"==a.toLowerCase()},i4=function(a){a.g&&a.J&&(a.g.ontimeout=null);
a.B&&(g.w.clearTimeout(a.B),a.B=null)},vpa=function(a){return g.Md&&g.Cc(9)&&g.Da(a.timeout)&&g.Ba(a.ontimeout)},j4=function(a){a.O||(a.O=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},k4=function(a,b){if(a.g){i4(a);
var c=a.g,d=a.P[0]?g.Fa:null;a.g=null;a.P=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},l4=function(a,b){a.i=!1;
a.g&&(a.o=!0,a.g.abort(),a.o=!1);a.l=b;a.u=5;j4(a);k4(a)},m4=function(a){return a.g?a.g.readyState:0},n4=function(a){if(a.i&&"undefined"!=typeof g.MX)if(a.P[1]&&4==m4(a)&&2==a.getStatus())h4(a,"Local request error detected and ignored");
else if(a.D&&4==m4(a))g.Dg(a.Qv,0,a);else if(a.dispatchEvent("readystatechange"),4==m4(a)){h4(a,"Request complete");a.i=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Ng(String(a.F))[1]||null;if(!f&&g.w.self&&g.w.self.location){var k=g.w.self.location.protocol;f=k.substr(0,k.length-1)}e=!wpa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.u=6;try{var l=2<m4(a)?a.g.statusText:""}catch(m){l=""}a.l=l+" ["+a.getStatus()+"]";j4(a)}}finally{k4(a)}}},o4=function(a){g.Qf.call(this);
this.headers=new g.Tm;this.M=a||null;this.i=!1;this.P=this.g=null;this.ba=this.F="";this.u=0;this.l="";this.o=this.V=this.D=this.O=!1;this.A=0;this.B=null;this.Y="";this.J=this.R=!1},p4=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},xpa=function(a,b){var c=[];
g.Vk(b,function(d){try{var e=g.Po.prototype.i.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.Ba(e)?g.Oo(e)&&c.push(d):c.push(d)},a);
return c},ypa=function(a,b){var c=xpa(a,b);
(0,g.B)(c,function(d){g.Po.prototype.remove.call(this,d)},a)},q4=function(a){if(a.Zc){if(a.Zc.locationOverrideToken)return{locationOverrideToken:a.Zc.locationOverrideToken};
if(null!=a.Zc.latitudeE7&&null!=a.Zc.longitudeE7)return{latitudeE7:a.Zc.latitudeE7,longitudeE7:a.Zc.longitudeE7}}return null},zpa=function(a,b){g.$a(a,b)||a.push(b)},r4=function(a){var b=0,c;
for(c in a)b++;return b},Apa=function(a){return/^\s*$/.test(a)?!1:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,""))},Bpa=function(a){try{return g.w.JSON.parse(a)}catch(d){var b=d}a=String(a);
if(Apa(a))try{var c=eval("("+a+")");b&&(0,g.MW)("Invalid JSON: "+a,b);return c}catch(d){}throw Error("Invalid JSON string: "+a);},Cpa=function(a,b,c,d){var e=new g.Wm(null,void 0);
a&&g.Xm(e,a);b&&g.Ym(e,b);c&&g.Zm(e,c);d&&(e.i=d);return e},s4=function(a){if(g.w.JSON)try{return g.w.JSON.parse(a)}catch(b){}return Bpa(a)},t4=function(){this.g=[];
this.i=[]},u4=function(a,b){g.Up[a]=!0;
var c=g.Sp();c&&c.publish.apply(c,arguments);g.Up[a]=!1},v4=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.l=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Tm;this.g=this.i="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",Dpa(this,a.capabilities||""),Epa(this,a.experiments||""),this.i=a.remoteControllerUrl||"",this.g=a.localChannelEncryptionKey||
"")},Dpa=function(a,b){a.capabilities.clear();
(0,g.Yd)(b.split(","),g.Qa(rpa,Fpa)).forEach(function(c){a.capabilities.add(c)})},Epa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},w4=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},x4=function(a,b){return!!b&&(a.id==b||a.uuid==b)},y4=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},Gpa=function(a){return new w4(a)},z4=function(a){return g.Ja(a)?(0,g.F)(a,Gpa):[]},A4=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},B4=function(a){return g.Ja(a)?"["+(0,g.F)(a,A4).join(",")+"]":"null"},C4=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},Hpa=function(a){return(0,g.F)(a,function(b){return{key:b.id,
name:b.name}})},D4=function(a,b){return g.Xa(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},E4=function(a,b){return g.Xa(a,function(c){return x4(c,b)})},Ipa=function(){var a=(0,g.dt)();
a&&ypa(a,a.g.df(!0))},F4=function(){var a=g.gt("yt-remote-connected-devices")||[];
g.qb(a);return a},Jpa=function(a){if(0==a.length)return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.F)(a,function(d,e){return 0==e?d:d.substring(c.length)})},G4=function(a){g.ft("yt-remote-connected-devices",a,86400)},I4=function(){if(H4)return H4;
var a=g.gt("yt-remote-device-id");a||(a=C4(),g.ft("yt-remote-device-id",a,31536E3));for(var b=F4(),c=1,d=a;g.$a(b,d);)c++,d=a+"#"+c;return H4=d},J4=function(){var a=F4(),b=I4();
g.$a(a,b);g.it()&&g.sb(a,b);a=Jpa(a);if(0==a.length)try{g.Fs("remote_sid")}catch(c){}else try{g.Es("remote_sid",a.join(","),-1)}catch(c){}},K4=function(){return g.gt("yt-remote-session-browser-channel")},L4=function(){return g.gt("yt-remote-local-screens")||[]},M4=function(){g.ft("yt-remote-lounge-token-expiration",!0,86400)},Kpa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.F)(L4(),function(d){return d.loungeToken}),c=(0,g.F)(a,function(d){return d.loungeToken});
(0,g.Ri)(c,function(d){return!g.$a(b,d)})&&M4();
g.ft("yt-remote-local-screens",a,31536E3)},Lpa=function(a,b){g.ft("yt-remote-session-browser-channel",a);
g.ft("yt-remote-session-screen-id",b);var c=F4(),d=I4();g.$a(c,d)||c.push(d);G4(c);J4()},N4=function(a){a||(g.ht("yt-remote-session-screen-id"),g.ht("yt-remote-session-video-id"));
J4();a=F4();g.cb(a,I4());G4(a)},P4=function(){if(!O4){var a=g.Zo();
a&&(O4=new g.Jo(a))}return O4?!!O4.get("yt-remote-use-staging-server"):!1},Q4=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},R4=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},T4=function(a){a.length?S4(a.shift(),function(){T4(a)}):U4()},Mpa=function(a){return"chrome-extension://"+a+V4},S4=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},U4=function(){var a=R4();
a&&a(!1,"No cast extension found")},W4=function(){if(Npa){var a=2,b=R4(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;S4("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",U4,c)}},Opa=function(){W4();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);T4(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+V4,"//www.gstatic.com/eureka/clank"+V4])},X4=function(a,b,c){g.G.call(this);
this.A=null!=c?(0,g.z)(a,c):a;this.Vc=b;this.u=(0,g.z)(this.QC,this);this.g=!1;this.i=0;this.l=this.za=null;this.o=[]},Y4=function(){},Z4=function(a,b,c,d){this.g=a;
this.l=b;this.B=c;this.A=d||1;this.o=45E3;this.ca=new g.kn(this);this.i=new g.Cg;this.i.setInterval(250)},a5=function(a,b,c){a.Nh=1;
a.cg=e4(b.clone());a.ih=c;a.u=!0;$4(a,null)},b5=function(a,b,c,d,e){a.Nh=1;
a.cg=e4(b.clone());a.ih=null;a.u=c;e&&(a.Ez=!1);$4(a,d)},$4=function(a,b){a.si=(0,g.C)();
c5(a);a.tg=a.cg.clone();f4(a.tg,"t",a.A);a.Mk=0;a.lc=a.g.cp(a.g.Fk()?b:null);0<a.Ip&&(a.nn=new g.Dl((0,g.z)(a.NA,a,a.lc),a.Ip));a.ca.da(a.lc,"readystatechange",a.yL);var c=a.Mg?g.bc(a.Mg):{};a.ih?(a.bo="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.lc.send(a.tg,a.bo,a.ih,c)):(a.bo="GET",a.Ez&&!g.Od&&(c.Connection="close"),a.lc.send(a.tg,a.bo,null,c));a.g.me(1)},j5=function(a,b,c){for(var d=!0;!a.Eg&&a.Mk<c.length;){var e=Ppa(a,c);
if(e==d5){4==b&&(a.dg=4,e5(15),d=!1);break}else if(e==f5){a.dg=4;e5(16);d=!1;break}else g5(a,e)}4==b&&0==c.length&&(a.dg=1,e5(17),d=!1);a.re=a.re&&d;d||(h5(a),i5(a))},Ppa=function(a,b){var c=a.Mk,d=b.indexOf("\n",c);
if(-1==d)return d5;c=Number(b.substring(c,d));if(isNaN(c))return f5;d+=1;if(d+c>b.length)return d5;var e=b.substr(d,c);a.Mk=d+c;return e},m5=function(a,b){a.si=(0,g.C)();
c5(a);var c=b?window.location.hostname:"";a.tg=a.cg.clone();g.dn(a.tg,"DOMAIN",c);g.dn(a.tg,"t",a.A);try{a.te=new ActiveXObject("htmlfile")}catch(n){h5(a);a.dg=7;e5(22);i5(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in k5)k=k5[l];else if(l in l5)k=k5[l]=l5[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
k5[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.jd(g.Kc("b/12014412"),d+"</body></html>");a.te.open();a.te.write(g.gd(c));a.te.close();a.te.parentWindow.m=(0,g.z)(a.SK,a);a.te.parentWindow.d=(0,g.z)(a.Ny,a,!0);a.te.parentWindow.rpcClose=(0,g.z)(a.Ny,a,!1);c=a.te.createElement("DIV");a.te.parentWindow.document.body.appendChild(c);d=g.Wc(a.tg.toString());d=g.nc(g.Tc(d));d=g.jd(g.Kc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.kd(c,d);a.g.me(1)},c5=function(a){a.Rs=(0,g.C)()+a.o;
n5(a,a.o)},n5=function(a,b){if(null!=a.Ki)throw Error("WatchDog timer not null");
a.Ki=o5((0,g.z)(a.cL,a),b)},p5=function(a){a.Ki&&(g.w.clearTimeout(a.Ki),a.Ki=null)},i5=function(a){a.g.Ov()||a.Eg||a.g.Xm(a)},h5=function(a){p5(a);
g.qf(a.nn);a.nn=null;a.i.stop();g.mn(a.ca);if(a.lc){var b=a.lc;a.lc=null;b.abort();b.dispose()}a.te&&(a.te=null)},g5=function(a,b){try{a.g.Hy(a,b),a.g.me(4)}catch(c){}},r5=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;q5(a,b,function(k){k?c(!0):g.w.setTimeout(function(){r5(a,b,c,d,f)},f)})}},q5=function(a,b,c){var d=new Image;
d.onload=function(){try{s5(d),c(!0)}catch(e){}};
d.onerror=function(){try{s5(d),c(!1)}catch(e){}};
d.onabort=function(){try{s5(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{s5(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},s5=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},t5=function(a){this.g=a;
this.i=new Y4},v5=function(a){var b=u5(a.g,a.Yi,"/mail/images/cleardot.gif");
e4(b);r5(b.toString(),5E3,(0,g.z)(a.aC,a),3,2E3);a.me(1)},x5=function(a){var b=a.g.F;
if(null!=b)e5(5),b?(e5(11),w5(a.g,a,!1)):(e5(12),w5(a.g,a,!0));else if(a.Bd=new Z4(a,void 0,void 0,void 0),a.Bd.Mg=a.Gp,b=a.g,b=u5(b,b.Fk()?a.Ej:null,a.Hp),e5(5),!g.Md||g.Dc(10))f4(b,"TYPE","xmlhttp"),b5(a.Bd,b,!1,a.Ej,!1);else{f4(b,"TYPE","html");var c=a.Bd;a=!!a.Ej;c.Nh=3;c.cg=e4(b.clone());m5(c,a)}},y5=function(a,b,c){this.g=1;
this.i=[];this.o=[];this.u=new Y4;this.D=a||null;this.F=null!=b?b:null;this.A=c||!1},Qpa=function(a,b){this.g=a;
this.map=b;this.context=null},z5=function(a){g.sf.call(this,"statevent",a)},A5=function(a,b){g.sf.call(this,"timingevent",a);
this.size=b},B5=function(a){g.sf.call(this,"serverreachability",a)},F5=function(a){C5(a);
if(3==a.g){var b=a.lk++,c=a.Jl.clone();g.dn(c,"SID",a.l);g.dn(c,"RID",b);g.dn(c,"TYPE","terminate");D5(a,c);b=new Z4(a,a.l,b,void 0);b.Nh=2;b.cg=e4(c.clone());(new Image).src=b.cg;b.si=(0,g.C)();c5(b)}E5(a)},H5=function(a){a.rC(1,0);
a.Jl=u5(a,null,a.Fp);G5(a)},C5=function(a){a.Tf&&(a.Tf.abort(),a.Tf=null);
a.Sb&&(a.Sb.cancel(),a.Sb=null);a.gf&&(g.w.clearTimeout(a.gf),a.gf=null);I5(a);a.yd&&(a.yd.cancel(),a.yd=null);a.Yf&&(g.w.clearTimeout(a.Yf),a.Yf=null)},J5=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new Qpa(a.aH++,b));2!=a.g&&3!=a.g||G5(a)},G5=function(a){a.yd||a.Yf||(a.Yf=o5((0,g.z)(a.My,a),0),a.Ih=0)},M5=function(a,b){if(1==a.g){if(!b){a.lk=Math.floor(1E5*Math.random());
var c=a.lk++,d=new Z4(a,"",c,void 0);d.Mg=null;var e=K5(a),f=a.Jl.clone();g.dn(f,"RID",c);g.dn(f,"CVER","1");D5(a,f);a5(d,f,e);a.yd=d;a.g=2}}else 3==a.g&&(b?L5(a,b):0==a.i.length||a.yd||L5(a))},L5=function(a,b){if(b)if(6<a.Fg){a.i=a.o.concat(a.i);
a.o.length=0;var c=a.lk-1;var d=K5(a)}else c=b.B,d=b.ih;else c=a.lk++,d=K5(a);var e=a.Jl.clone();g.dn(e,"SID",a.l);g.dn(e,"RID",c);g.dn(e,"AID",a.Yh);D5(a,e);c=new Z4(a,a.l,c,a.Ih+1);c.Mg=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.yd=c;a5(c,e,d)},D5=function(a,b){if(a.Tc){var c=a.Tc.uv();
c&&g.Kb(c,function(d,e){g.dn(b,e,d)})}},K5=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Fg&&0<b){var d=a.i[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.i[e].g,k=a.i[e].map;f=6>=a.Fg?e:f-d;try{g.Kb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.o=a.o.concat(a.i.splice(0,b));
return c.join("&")},N5=function(a){a.Sb||a.gf||(a.B=1,a.gf=o5((0,g.z)(a.Ly,a),0),a.Ch=0)},P5=function(a){if(a.Sb||a.gf||3<=a.Ch)return!1;
a.B++;a.gf=o5((0,g.z)(a.Ly,a),O5(a,a.Ch));a.Ch++;return!0},w5=function(a,b,c){a.Yn=c;
a.Ee=b.uf;a.A||H5(a)},I5=function(a){null!=a.Ig&&(g.w.clearTimeout(a.Ig),a.Ig=null)},O5=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},R5=function(a,b){if(2==b||9==b){var c=null;
a.Tc&&(c=null);var d=(0,g.z)(a.aM,a);c||(c=new g.Wm("//www.google.com/images/cleardot.gif"),e4(c));q5(c.toString(),1E4,d)}else e5(2);Q5(a,b)},Q5=function(a,b){a.g=0;
a.Tc&&a.Tc.tu(b);E5(a);C5(a)},E5=function(a){a.g=0;
a.Ee=-1;if(a.Tc)if(0==a.o.length&&0==a.i.length)a.Tc.Qo();else{g.gb(a.o);var b=g.gb(a.i);a.o.length=0;a.i.length=0;a.Tc.Qo(b)}},u5=function(a,b,c){var d=g.en(c);
if(""!=d.g)b&&g.Ym(d,b+"."+d.g),g.Zm(d,d.u);else{var e=window.location;d=Cpa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.lj&&g.Kb(a.lj,function(f,k){g.dn(d,k,f)});
g.dn(d,"VER",a.Fg);D5(a,d);return d},o5=function(a,b){if(!g.Ma(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},e5=function(a){S5.dispatchEvent(new z5(S5,a))},T5=function(){},Rpa=function(a,b){this.action=a;
this.params=b||{}},U5=function(a,b){g.G.call(this);
this.g=new g.M(this.KK,0,this);g.H(this,this.g);this.Vc=5E3;this.i=0;if(g.Ma(a))b&&(a=(0,g.z)(a,b));else if(a&&g.Ma(a.handleEvent))a=(0,g.z)(a.handleEvent,a);else throw Error("Invalid listener argument");this.l=a},V5=function(a,b,c){this.H=a;
this.A=b;this.l=new g.Io;this.i=new U5(this.tM,this);this.g=null;this.ab=!1;this.u=null;this.F="";this.D=this.o=0;this.B=[];this.J=c||!1},Spa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Yn,sessionId:a.g.l,arrayId:a.g.Yh}},W5=function(a,b){a.D=b||0;
a.i.stop();a.g&&(3==a.g.g&&M5(a.g),F5(a.g));a.D=0},X5=function(a){return!!a.g&&3==a.g.g},Tpa=function(a,b){(a.A.loungeIdToken=b)||a.i.stop()},Y5=function(a){this.port=this.domain="";
this.g="/api/lounge";this.i=!0;a=a||document.location.href;var b=g.Qg(a)||"";b&&(this.port=":"+b);this.domain=g.Pg(a)||"";a=g.Ib;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Hb(a,"10.0")&&(this.i=!1))},Z5=function(a,b){var c=a.g;
if(g.Ba(void 0)?0:a.i)c="https://"+a.domain+a.port+a.g;return g.Zg(c+b,{})},$5=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Qa(a.o,d,!0),onError:g.Qa(a.l,e),md:g.Qa(a.u,e)};c&&(a.qb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Eq(b,a)},Upa=function(){var a=a6;
b6();c6.push(a);d6(c6)},e6=function(a,b){b6();
var c=c6,d=Vpa(a,String(b));0==c.length?Wpa(d):(d6(c),(0,g.B)(c,function(e){e(d)}))},b6=function(){c6||(c6=g.x("yt.mdx.remote.debug.handlers_")||[],g.Ea("yt.mdx.remote.debug.handlers_",c6,void 0))},Wpa=function(a){var b=(f6+1)%50;
f6=b;g6[b]=a;h6||(h6=49==b)},d6=function(a){var b=g6;
if(b[0]){var c=f6,d=h6?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.B)(a,function(f){f(e)})}while(d!=c);
g6=Array(50);f6=-1;h6=!1}},Vpa=function(a,b){var c=((0,g.C)()-Xpa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},i6=function(a){g.O.call(this);
this.B=a;this.g=[]},j6=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},Ypa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Yd)(a.g,function(f){return!!D4(b,f)});
for(var d=0,e=b.length;d<e;d++)c=j6(a,b[d])||c;return c},Zpa=function(a,b){var c=a.g.length;
a.g=(0,g.Yd)(a.g,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.g.length<c},k6=function(a,b,c,d){g.O.call(this);
this.A=a;this.u=b;this.l=c;this.o=d;this.i=0;this.g=null;this.za=NaN},m6=function(a){i6.call(this,"LocalScreenService");
this.l=a;this.i=NaN;l6(this);this.info("Initializing with "+B4(this.g))},n6=function(a){if(a.g.length){var b=(0,g.F)(a.g,function(d){return d.id}),c=Z5(a.l,"/pairing/get_lounge_token_batch");
$5(a.l,c,{screen_ids:b.join(",")},(0,g.z)(a.aD,a),(0,g.z)(a.ZC,a))}},l6=function(a){var b=z4(L4());
b=(0,g.Yd)(b,function(c){return!c.uuid});
return Ypa(a,b)},o6=function(a,b){Kpa((0,g.F)(a.g,y4));
b&&M4()},q6=function(a,b){g.O.call(this);
this.A=b;var c=g.gt("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.A(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.$a(c,l)}this.g=d;this.u=a;this.l=this.o=NaN;this.i=null;p6("Initialized with "+g.Hg(this.g))},r6=function(a,b,c){var d=Z5(a.u,"/pairing/get_screen_availability");
$5(a.u,d,{lounge_token:b.token},(0,g.z)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.z)(function(){c(!1)},a))},s6=function(a,b){a:if(r4(b)!=r4(a.g))var c=!1;
else{c=g.Rb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(p6("Updated online screens: "+g.Hg(a.g)),a.g=b,a.N("screenChange"));$pa(a)},t6=function(a){isNaN(a.l)||g.Rp(a.l);
a.l=g.Pp((0,g.z)(a.Tr,a),0<a.o&&a.o<(0,g.C)()?2E4:1E4)},p6=function(a){e6("OnlineScreenService",a)},u6=function(a){var b={};
(0,g.B)(a.A(),function(c){c.token?b[c.token]=c.id:this.Kb("Requesting availability of screen w/o lounge token.")});
return b},$pa=function(a){a=g.Rb(g.Lb(a.g,function(b){return b}));
g.qb(a);a.length?g.ft("yt-remote-online-screen-ids",a.join(","),60):g.ht("yt-remote-online-screen-ids")},v6=function(a){i6.call(this,"ScreenService");
this.A=a;this.i=this.l=null;this.o=[];this.u={};aqa(this)},x6=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.u[b]);var k=a.Gd();if(k=(c?E4(k,c):null)||E4(k,b)){k.uuid=b;var l=w6(a,k);r6(a.i,l,function(m){e(m?l:null)})}else c?bqa(a,c,(0,g.z)(function(m){var n=w6(this,new w4({name:d,
screenId:c,loungeToken:m,dialId:b||""}));r6(this.i,n,function(p){e(p?n:null)})},a),f):e(null)},y6=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},bqa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={qb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Eq(Z5(a.A,"/pairing/get_lounge_token_batch"),e)},z6=function(a){a.g=a.l.Gd();
var b=a.u,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+B4(a.g))},aqa=function(a){A6(a);
a.l=new m6(a.A);a.l.subscribe("screenChange",(0,g.z)(a.jD,a));z6(a);a.o=z4(g.gt("yt-remote-automatic-screen-cache")||[]);A6(a);a.info("Initializing automatic screens: "+B4(a.o));a.i=new q6(a.A,(0,g.z)(a.Gd,a,!0));a.i.subscribe("screenChange",(0,g.z)(function(){this.N("onlineScreenChange")},a))},w6=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=E4(a.o,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.o.push(b),g.ft("yt-remote-automatic-screen-cache",(0,g.F)(a.o,y4)));A6(a);a.u[b.uuid]=b.id;g.ft("yt-remote-device-id-map",a.u,31536E3);return b},A6=function(a){a.u=g.gt("yt-remote-device-id-map")||{}},B6=function(a,b,c){g.O.call(this);
this.P=c;this.F=a;this.i=b;this.l=null},C6=function(a,b){e6(a.P,b)},E6=function(a,b){B6.call(this,a,b,"CastSession");
this.g=null;this.o=0;this.A=(0,g.z)(this.zM,this);this.u=(0,g.z)(this.nL,this);this.o=g.Pp((0,g.z)(function(){D6(this,null)},this),12E4)},cqa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Hg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Fa,(0,g.z)(function(){C6(this,"Failed to send message: getMdxSessionStatus.")},a)):C6(a,"Sending yt message without session: "+g.Hg(b))},D6=function(a,b){g.Rp(a.o);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.l||a.l.id!=b){var c=(0,g.z)(a.Ym,a),d=(0,g.z)(a.Jd,a);a.Hv(b,c,d,5)}}else a.Jd(Error("Waiting for session status timed out."))},F6=function(a,b,c){B6.call(this,a,b,"DialSession");
this.o=this.D=null;this.H="";this.M=c;this.u=null;this.B=g.Fa;this.A=NaN;this.J=(0,g.z)(this.CM,this);this.g=g.Fa},G6=function(a){a.g=a.F.SA(a.H,a.i.label,a.i.friendlyName,(0,g.z)(function(b){this.g=g.Fa;
this.Ym(b)},a),(0,g.z)(function(b){this.g=g.Fa;
this.Jd(b)},a))},H6=function(a){var b={};
b.pairingCode=a.H;b.theme=a.M;if(a.u){var c=a.u.currentTime||0;b.v=a.u.videoId;b.t=c}P4()&&(b.env_useStageMdx=1);return g.Xg(b)},I6=function(a,b){B6.call(this,a,b,"ManualSession");
this.g=g.Pp((0,g.z)(this.ai,this,null),150)},J6=function(a,b,c,d){g.O.call(this);
this.i=a;this.B=b||"233637DE";this.A=c||"cl";this.D=d||!1;this.g=null;this.u=!1;this.l=[];this.o=(0,g.z)(this.TJ,this)},K6=function(a,b){return b?g.Xa(a.l,function(c){return x4(b,c.label)},a):null},L6=function(a){e6("Controller",a)},a6=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},M6=function(a){return a.u||!!a.l.length||!!a.g},N6=function(a,b,c){b!=a.g&&(g.qf(a.g),(a.g=b)?(c?a.N("yt-remote-cast2-receiver-resumed",b.i):a.N("yt-remote-cast2-receiver-selected",
b.i),b.subscribe("sessionScreen",(0,g.z)(a.Ky,a,b)),b.l?a.N("yt-remote-cast2-session-change",b.l):c&&a.g.ai(null)):a.N("yt-remote-cast2-session-change",null))},O6=function(a){var b=a.i.RA(),c=a.g&&a.g.i;
a=(0,g.F)(b,function(d){c&&x4(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=K6(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},gqa=function(a,b,c,d,e,f,k){dqa()?eqa(b,e,f,k)&&(Q6(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?R6(a,c):(window.__onGCastApiAvailable=function(l,m){l?R6(a,c):(S6("Failed to load cast API: "+m),T6(!1),Q6(!1),g.ht("yt-remote-cast-available"),g.ht("yt-remote-cast-receiver"),U6(),c(!1))},d?g.bq("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?Opa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?U4():(W4(),T4(fqa.map(Mpa))))):P6("Cannot initialize because not running Chrome")},U6=function(){P6("dispose");
var a=V6();a&&a.dispose();g.Ea("yt.mdx.remote.cloudview.instance_",null,void 0);W6(!1);g.Xp(X6);X6.length=0},Y6=function(){return!!g.gt("yt-remote-cast-installed")},Z6=function(){var a=g.gt("yt-remote-cast-receiver");
return a?a.friendlyName:null},$6=function(){P6("clearCurrentReceiver");
g.ht("yt-remote-cast-receiver")},a7=function(){return Y6()?V6()?V6().getCastSession():(S6("getCastSelector: Cast is not initialized."),null):(S6("getCastSelector: Cast API is not installed!"),null)},c7=function(){Y6()?V6()?b7()?(P6("Requesting cast selector."),V6().requestSession()):(P6("Wait for cast API to be ready to request the session."),X6.push(g.Wp("yt-remote-cast2-api-ready",c7))):S6("requestCastSelector: Cast is not initialized."):S6("requestCastSelector: Cast API is not installed!")},d7=
function(a,b){b7()?V6().setConnectedScreenStatus(a,b):S6("setConnectedScreenStatus called before ready.")},dqa=function(){var a=0<=g.Ib.search(/ (CrMo|Chrome|CriOS)\//);
return g.Mw||a},hqa=function(a,b){V6().init(a,b)},eqa=function(a,b,c,d){var e=!1;
V6()||(a=new J6(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.ft("yt-remote-cast-available",f);u4("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){P6("onReceiverSelected: "+f.friendlyName);
g.ft("yt-remote-cast-receiver",f);u4("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){P6("onReceiverResumed: "+f.friendlyName);
g.ft("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){P6("onSessionChange: "+A4(f));
f||g.ht("yt-remote-cast-receiver");u4("yt-remote-cast2-session-change",f)}),g.Ea("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
P6("cloudview.createSingleton_: "+e);return e},V6=function(){return g.x("yt.mdx.remote.cloudview.instance_")},R6=function(a,b){T6(!0);
Q6(!1);hqa(a,function(c){c?(W6(!0),g.Zp("yt-remote-cast2-api-ready")):(S6("Failed to initialize cast API."),T6(!1),g.ht("yt-remote-cast-available"),g.ht("yt-remote-cast-receiver"),U6());b(c)})},P6=function(a){e6("cloudview",a)},S6=function(a){e6("cloudview",a)},T6=function(a){P6("setCastInstalled_ "+a);
g.ft("yt-remote-cast-installed",a)},b7=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},W6=function(a){P6("setApiReady_ "+a);
g.Ea("yt.mdx.remote.cloudview.apiReady_",a,void 0)},Q6=function(a){g.Ea("yt.mdx.remote.cloudview.initializing_",a,void 0)},e7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.A=this.B=0;this.g=null;this.hasNext=this.Ge=!1;this.F=this.D=this.i=this.o=0;this.l=NaN;this.u=!1;this.reset(a)},f7=function(a){a.audioTrackId=null;
a.g=null;a.playerState=-1;a.Ge=!1;a.hasNext=!1;a.B=0;a.A=(0,g.C)();a.o=0;a.i=0;a.D=0;a.F=0;a.l=NaN;a.u=!1},g7=function(a){return 1==a.playerState?((0,g.C)()-a.A)/1E3:0},h7=function(a,b){a.B=b;
a.A=(0,g.C)()},i7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.C)()-a.A)/1E3+a.B;
case -1E3:return 0}return a.B},j7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&f7(a)},k7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.cc(a.g);b.hasPrevious=a.Ge;b.hasNext=a.hasNext;b.playerTime=a.B;b.playerTimeAt=a.A;b.seekableStart=a.o;b.seekableEnd=a.i;b.duration=a.D;b.loadedTime=a.F;b.liveIngestionTime=a.l;return b},n7=function(a,b){g.O.call(this);
this.g=0;this.o=a;this.A=[];this.u=new t4;this.l=this.i=null;this.F=(0,g.z)(this.LH,this);this.B=(0,g.z)(this.mk,this);this.D=(0,g.z)(this.KH,this);this.H=(0,g.z)(this.XH,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Us,this),l7(this))):c=3;0!=c&&(b?this.Us(c):g.Pp((0,g.z)(function(){this.Us(c)},this),0));
var d=a7();d&&m7(this,d);this.subscribe("yt-remote-cast2-session-change",this.H)},o7=function(a){return new e7(a.o.getPlayerContextData())},l7=function(a){(0,g.B)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.A.push(this.o.subscribe(b,g.Qa(this.QJ,b),this))},a)},p7=function(a){(0,g.B)(a.A,function(b){this.o.unsubscribeByKey(b)},a);
a.A.length=0},q7=function(a,b){var c=a.u;
50>c.g.length+c.i.length&&a.u.i.push(b)},s7=function(a,b,c){var d=o7(a);
h7(d,c);-1E3!=d.playerState&&(d.playerState=b);r7(a,d)},t7=function(a,b,c){a.o.sendMessage(b,c)},r7=function(a,b){p7(a);
a.o.setPlayerContextData(k7(b));l7(a)},m7=function(a,b){a.l&&(a.l.removeUpdateListener(a.F),a.l.removeMediaListener(a.B),a.mk(null));
a.l=b;a.l&&(e6("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.F),a.l.addMediaListener(a.B),a.l.media.length&&a.mk(a.l.media[0]))},u7=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=o7(a);b.contentId!=d.videoId&&e6("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;h7(d,a.i.getEstimatedTime());r7(a,d)}else e6("CP","No cast media video. Ignoring state update.")},v7=function(a,b,c){return(0,g.z)(function(d){this.Kb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Kb("Retrying "+b+" using MDx browser channel."),t7(this,b,c))},a)},w7=function(a,b,c){g.O.call(this);
this.u=NaN;this.M=!1;this.H=this.F=this.J=this.P=NaN;this.O=[];this.o=this.B=this.l=this.Pa=this.g=null;this.na=a;this.O.push(g.Dr(window,"beforeunload",(0,g.z)(this.TC,this)));this.i=[];this.Pa=new e7;this.V=b.id;this.g=iqa(this,c);this.g.subscribe("handlerOpened",this.PH,this);this.g.subscribe("handlerClosed",this.MH,this);this.g.subscribe("handlerError",this.NH,this);this.g.subscribe("handlerMessage",this.OH,this);Tpa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Pa.videoId;
g.it()&&g.ft("yt-remote-session-video-id",d)},this)},x7=function(a){e6("conn",a)},iqa=function(a,b){return new V5(Z5(a.na,"/bc"),b)},y7=function(a,b){a.N("proxyStateChange",b)},jqa=function(a){a.u=g.Pp((0,g.z)(function(){x7("Connecting timeout");
this.A(1)},a),2E4)},z7=function(a){g.Rp(a.u);
a.u=NaN},A7=function(a){g.Rp(a.P);
a.P=NaN},kqa=function(a){B7(a);
a.J=g.Pp((0,g.z)(function(){C7(this,"getNowPlaying")},a),2E4)},B7=function(a){g.Rp(a.J);
a.J=NaN},E7=function(a,b){b&&(z7(a),A7(a));
b==(X5(a.g)&&isNaN(a.u))?b&&(y7(a,1),C7(a,"getSubtitlesTrack")):b?(a.R()&&a.Pa.reset(),y7(a,1),C7(a,"getNowPlaying"),D7(a)):a.A(1)},lqa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Pa.videoId&&(g.Xb(b.params)?a.Pa.g=null:a.Pa.g=b.params,a.N("remotePlayerChange"))},F7=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Pa.listId=b.params.listId||a.Pa.listId;j7(a.Pa,c,d);a.N("remoteQueueChange")},mqa=function(a,b){b.params=b.params||{};
F7(a,b);G7(a,b);a.N("autoplayDismissed")},G7=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
h7(a.Pa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Pa.playerState&&(c=-1E3);a.Pa.playerState=c;c=Number(b.params.loadedTime);a.Pa.F=isNaN(c)?0:c;c=Number(b.params.duration);a.Pa.D=isNaN(c)?0:c;c=a.Pa;var d=Number(b.params.liveIngestionTime);c.l=d;c.u=isNaN(d)?!1:!0;c=a.Pa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.o=isNaN(d)?0:d;c.i=isNaN(e)?0:e;1==a.Pa.playerState?kqa(a):B7(a);a.N("remotePlayerChange")},nqa=function(a,b){if(-1E3!=
a.Pa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Pa.playerState=c;c=parseInt(b.params.currentTime,10);h7(a.Pa,isNaN(c)?0:c);a.N("remotePlayerChange")}},oqa=function(a,b){var c="true"==b.params.muted;
a.Pa.volume=parseInt(b.params.volume,10);a.Pa.muted=c;a.N("remotePlayerChange")},pqa=function(a,b){a.B=b.params.videoId;
a.N("nowAutoplaying",parseInt(b.params.timeout,10))},qqa=function(a,b){var c="true"==b.params.hasNext;
a.Pa.Ge="true"==b.params.hasPrevious;a.Pa.hasNext=c;a.N("previousNextChange")},D7=function(a){g.Rp(a.H);
a.H=g.Pp((0,g.z)(a.A,a,1),864E5)},C7=function(a,b,c){c?x7("Sending: action="+b+", params="+g.Hg(c)):x7("Sending: action="+b);
a.g.sendMessage(b,c)},H7=function(a){i6.call(this,"ScreenServiceProxy");
this.Fc=a;this.i=[];this.i.push(this.Fc.$_s("screenChange",(0,g.z)(this.xM,this)));this.i.push(this.Fc.$_s("onlineScreenChange",(0,g.z)(this.uJ,this)))},vqa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.Hp("MDX_CONFIG")||b;Ipa();J4();I7||(I7=new Y5(b?b.loungeApiHost:void 0),P4()&&(I7.g="/api/loungedev"));J7||(J7=g.x("yt.mdx.remote.deferredProxies_")||[],g.Ea("yt.mdx.remote.deferredProxies_",J7,void 0));rqa();var c=K7();if(!c){var d=new v6(I7);g.Ea("yt.mdx.remote.screenService_",d,void 0);c=K7();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);gqa(a,d,function(m){m?L7()&&d7(L7(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){u4("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.Ea("yt.mdx.remote.initialized_",!0,void 0),M7("Initializing: "+g.Hg(b)),N7.push(g.Wp("yt-remote-cast2-availability-change",function(){u4("yt-remote-receiver-availability-change")})),N7.push(g.Wp("yt-remote-cast2-receiver-selected",function(){O7(null);
u4("yt-remote-auto-connect","cast-selector-receiver")})),N7.push(g.Wp("yt-remote-cast2-receiver-resumed",function(){u4("yt-remote-receiver-resumed","cast-selector-receiver")})),N7.push(g.Wp("yt-remote-cast2-session-change",sqa)),N7.push(g.Wp("yt-remote-connection-change",function(m){m?d7(L7(),"YouTube TV"):P7()||(d7(null,null),$6())})),a=Q7(),b.isAuto&&(a.id+="#dial"),g.vq("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),M7(" -- with channel params: "+
g.Hg(a)),tqa(a),c.start(),L7()||uqa())},wqa=function(){var a=R7();
Y6()&&g.gt("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},R7=function(){var a=K7().Fc.$_gos();
var b=S7();b&&T7()&&(D4(a,b)||a.push(b));return Hpa(a)},U7=function(){var a=xqa();
!a&&Y6()&&Z6()&&(a={key:"cast-selector-receiver",name:Z6()});return a},xqa=function(){var a=R7(),b=S7();
b||(b=P7());return g.Xa(a,function(c){return b&&x4(b,c.key)?!0:!1})},S7=function(){var a=L7();
if(!a)return null;var b=K7().Gd();return E4(b,a)},sqa=function(a){M7("remote.onCastSessionChange_: "+A4(a));
if(a){var b=S7();b&&b.id==a.id?d7(b.id,"YouTube TV"):(b&&V7(),W7(a,1))}else T7()&&V7()},V7=function(){b7()?V6().stopSession():S6("stopSession called before API ready.");
var a=T7();a&&(a.disconnect(1),X7(null))},Y7=function(){var a=T7();
return!!a&&3!=a.getProxyState()},M7=function(a){e6("remote",a)},K7=function(){if(!Z7){var a=g.x("yt.mdx.remote.screenService_");
Z7=a?new H7(a):null}return Z7},L7=function(){return g.x("yt.mdx.remote.currentScreenId_")},$7=function(a){g.Ea("yt.mdx.remote.currentScreenId_",a,void 0)},a8=function(){return g.x("yt.mdx.remote.connectData_")},O7=function(a){g.Ea("yt.mdx.remote.connectData_",a,void 0)},T7=function(){return g.x("yt.mdx.remote.connection_")},X7=function(a){var b=T7();
O7(null);a||$7("");g.Ea("yt.mdx.remote.connection_",a,void 0);J7&&((0,g.B)(J7,function(c){c(a)}),J7.length=0);
b&&!a?u4("yt-remote-connection-change",!1):!b&&a&&u4("yt-remote-connection-change",!0)},P7=function(){var a=g.it();
if(!a)return null;var b=K7().Gd();return E4(b,a)},W7=function(a,b){S7()&&S7();
$7(a.id);var c=new w7(I7,a,Q7());c.connect(b,a8());c.subscribe("beforeDisconnect",function(d){u4("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){T7()&&X7(null)});
X7(c)},uqa=function(){var a=P7();
a?(M7("Resume connection to: "+A4(a)),W7(a,0)):(N4(),$6(),M7("Skipping connecting because no session screen found."))},rqa=function(){var a=Q7();
if(g.Xb(a)){a=I4();var b=g.gt("yt-remote-session-name")||"",c=g.gt("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ea("yt.mdx.remote.channelParams_",a,void 0)}},Q7=function(){return g.x("yt.mdx.remote.channelParams_")||{}},tqa=function(a){a?(g.ft("yt-remote-session-app",a.app),g.ft("yt-remote-session-name",a.name)):(g.ht("yt-remote-session-app"),g.ht("yt-remote-session-name"));
g.Ea("yt.mdx.remote.channelParams_",a,void 0)},b8=function(a,b,c){g.G.call(this);
this.u=a;this.i=b;this.l=new g.Qr(this);g.H(this,this.l);this.l.K(b,"onCaptionsTrackListChanged",this.KI);this.l.K(b,"captionschanged",this.JH);this.l.K(b,"captionssettingschanged",this.eA);this.l.K(b,"videoplayerreset",this.Zm);this.l.K(b,"mdxautoplaycancel",this.ZB);this.O=this.l.K(b,"onVolumeChange",this.uy);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.Gy,this);c.subscribe("remotePlayerChange",this.pk,this);c.subscribe("remoteQueueChange",this.Zm,this);c.subscribe("autoplayUpNext",this.hy,
this);c.subscribe("previousNextChange",this.Dy,this);c.subscribe("nowAutoplaying",this.zy,this);c.subscribe("autoplayDismissed",this.gy,this);this.suggestion=null;this.F=new g.EC(64);this.o=new g.M(this.cA,500,this);g.H(this,this.o);this.A=new g.M(this.dA,1E3,this);g.H(this,this.A);this.J=new X4(this.iM,0,this);g.H(this,this.J);this.B={};this.P=new g.M(this.DA,1E3,this);g.H(this,this.P);this.H=new g.Dl(this.oF,1E3,this);g.H(this,this.H);this.M=g.Fa;this.eA();this.Zm();this.pk()},c8=function(a,b){a.u.pd(b,
a.i.getVideoData().lengthSeconds)},e8=function(a){c8(a,0);
a.o.stop();d8(a,new g.EC(64))},g8=function(a,b){if(f8(a)&&!a.D){var c=null;
b&&(c={style:a.i.getSubtitlesUserSettings()},g.ec(c,b));a.g.Sz(a.i.getVideoData(1).videoId,c);a.B=o7(a.g).g}},h8=function(a,b){var c=a.i.getPlaylist();
if(c){var d=c.Ta;var e=c.listId.toString()}c=a.i.getVideoData(1);a.g.playVideo(c.videoId,b,d,e,c.playerParams,c.Th,q4(c));d8(a,new g.EC(1))},i8=function(a,b){if(b){var c=a.i.getOption("captions","tracklist",{UP:1});
c&&c.length?(a.i.setOption("captions","track",b),a.D=!1):(a.i.loadModule("captions"),a.D=!0)}else a.i.setOption("captions","track",{})},f8=function(a){return o7(a.g).videoId==a.i.getVideoData(1).videoId},d8=function(a,b){a.A.stop();
var c=a.F;if(!g.KC(c,b)){var d=g.U(b,2);d!=g.U(a.F,2)&&g.yJ(a.i,d);a.F=b;j8(a.u,c,b)}},l8=function(a){g.T.call(this,{C:"div",
G:"ytp-remote",I:[{C:"div",G:"ytp-remote-display-status",I:[{C:"div",G:"ytp-remote-display-status-icon",I:[g.LO()]},{C:"div",G:"ytp-remote-display-status-text",U:"{{statustext}}"}]}]});this.l=new g.vP(this,250);g.H(this,this.l);this.o=a;this.K(a,"presentingplayerstatechange",this.u);k8(this,g.uJ(a))},k8=function(a,b){if(3==a.o.getPresentingPlayerType()){var c={RECEIVER_NAME:a.o.getOption("remote","currentReceiver").name};
c=g.U(b,128)?g.KM("Error on $RECEIVER_NAME",c):g.LC(b)||g.U(b,4)?g.KM("Playing on $RECEIVER_NAME",c):g.KM("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},m8=function(a,b){g.dT.call(this,"Play on",0,a,b);
this.l=a;this.F={};this.K(a,"onMdxReceiversChange",this.J);this.K(a,"presentingplayerstatechange",this.J);this.J()},n8=function(a){g.ZJ.call(this,a);
this.i={key:C4(),name:"This computer"};this.o=null;this.u=[];this.B=this.g=null;this.A=[this.i];this.l=this.i;this.ak=new g.EC(64);this.D=0;this.om=-1;if(!g.Ky(g.V(this.player))){a=this.player;var b=g.cC(a);b&&(b=b.Jm())&&(b=new m8(a,b),g.H(this,b));b=new l8(a);g.H(this,b);g.LJ(a,b.element,4)}},j8=function(a,b,c){a.ak=c;
a.player.N("presentingplayerstatechange",new g.PC(c,b))},o8=function(a,b){if(b.key!=a.l.key)if(b.key==a.i.key)V7();
else{a.l=b;var c=a.player.getPlaylistId();var d=a.player.getVideoData(1);var e=d.videoId;if(c||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.oa(l).videoId}else k=[e];f=a.player.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.Th,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(d=q4(d))&&(c.locationInfo=d);d=c}else d=null;M7("Connecting to: "+g.Hg(b));"cast-selector-receiver"==b.key?
(O7(d||null),b7()?V6().setLaunchParams(d||null):S6("setLaunchParams called before ready.")):!d&&Y7()&&L7()==b.key?u4("yt-remote-connection-change",!0):(V7(),O7(d||null),d=K7().Gd(),(d=E4(d,b.key))&&W7(d,1))}},wpa=/^https?$/i,yqa=["POST",
"PUT"];g.A(o4,g.Qf);g.h=o4.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.F+"; newUri="+a);b=b?b.toUpperCase():"GET";this.F=a;this.l="";this.u=0;this.ba=b;this.O=!1;this.i=!0;this.g=this.M?g4(this.M):g4(g.jY);this.P=this.M?this.M.getOptions():g.jY.getOptions();this.g.onreadystatechange=(0,g.z)(this.Qv,this);try{d4(h4(this,"Opening Xhr")),this.V=!0,this.g.open(b,String(a),!0),this.V=!1}catch(f){d4(h4(this,"Error opening Xhr: "+f.message));l4(this,f);return}a=c||
"";var e=this.headers.clone();d&&tpa(d,function(f,k){e.set(k,f)});
d=g.Xa(e.Fd(),upa);c=g.w.FormData&&a instanceof g.w.FormData;!g.$a(yqa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.g.setRequestHeader(k,f)},this);
this.Y&&(this.g.responseType=this.Y);"withCredentials"in this.g&&this.g.withCredentials!==this.R&&(this.g.withCredentials=this.R);try{i4(this),0<this.A&&(this.J=vpa(this.g),d4(h4(this,"Will abort after "+this.A+"ms if incomplete, xhr2 "+this.J)),this.J?(this.g.timeout=this.A,this.g.ontimeout=(0,g.z)(this.Rv,this)):this.B=g.Dg(this.Rv,this.A,this)),d4(h4(this,"Sending request")),this.D=!0,this.g.send(a),this.D=!1}catch(f){d4(h4(this,"Send error: "+f.message)),l4(this,f)}};
g.h.Rv=function(){"undefined"!=typeof g.MX&&this.g&&(this.l="Timed out after "+this.A+"ms, aborting",this.u=8,h4(this,this.l),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.i&&(h4(this,"Aborting"),this.i=!1,this.o=!0,this.g.abort(),this.o=!1,this.u=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),k4(this))};
g.h.T=function(){this.g&&(this.i&&(this.i=!1,this.o=!0,this.g.abort(),this.o=!1),k4(this,!0));o4.Ha.T.call(this)};
g.h.Qv=function(){this.ea()||(this.V||this.D||this.o?n4(this):this.SJ())};
g.h.SJ=function(){n4(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<m4(this)?this.g.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return g.v(this.l)?this.l:String(this.l)};
var l5={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},k5={"'":"\\'"},zqa={};g.h=t4.prototype;g.h.isEmpty=function(){return 0==this.g.length&&0==this.i.length};
g.h.clear=function(){this.g=[];this.i=[]};
g.h.contains=function(a){return g.$a(this.g,a)||g.$a(this.i,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.bma)(b,a);0<=c?(g.bb(b,c),b=!0):b=!1;return b||g.cb(this.i,a)};
g.h.tc=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.i.length;for(b=0;b<c;++b)a.push(this.i[b]);return a};
var Fpa={WM:"atp",jP:"ska",YO:"que",wO:"mus",iP:"sus",NN:"dsp",fP:"seq"};v4.prototype.Uf=function(){var a=new v4({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.l=this.l;a.i=this.i;a.g=this.g};
var O4,H4="",V4=Q4("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",Npa=Q4("loadCastFramework")||Q4("loadCastApplicationFramework"),fqa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.A(X4,g.G);g.h=X4.prototype;g.h.PC=function(a){this.o=arguments;this.g=!1;this.za?this.l=(0,g.C)()+this.Vc:this.za=g.Dg(this.u,this.Vc)};
g.h.stop=function(){this.za&&(g.w.clearTimeout(this.za),this.za=null);this.l=null;this.g=!1;this.o=[]};
g.h.pause=function(){++this.i};
g.h.resume=function(){this.i&&(--this.i,!this.i&&this.g&&(this.g=!1,this.A.apply(null,this.o)))};
g.h.T=function(){this.stop();X4.Ha.T.call(this)};
g.h.QC=function(){this.l?(this.za=g.Dg(this.u,this.l-(0,g.C)()),this.l=null):(this.za=null,this.i?this.g=!0:(this.g=!1,this.A.apply(null,this.o)))};Y4.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
Y4.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};g.h=Z4.prototype;g.h.Mg=null;g.h.re=!1;g.h.Ki=null;g.h.Rs=null;g.h.si=null;g.h.Nh=null;g.h.cg=null;g.h.tg=null;g.h.ih=null;g.h.lc=null;g.h.Mk=0;g.h.te=null;g.h.bo=null;g.h.dg=null;g.h.Fj=-1;g.h.Ez=!0;g.h.Eg=!1;g.h.Ip=0;g.h.nn=null;var f5={},d5={};g.h=Z4.prototype;g.h.setTimeout=function(a){this.o=a};
g.h.yL=function(a){a=a.target;var b=this.nn;b&&3==m4(a)?b.Bj():this.NA(a)};
g.h.NA=function(a){try{if(a==this.lc)a:{var b=m4(this.lc),c=this.lc.u,d=this.lc.getStatus();if(g.Md&&!g.Dc(10)||g.Od&&!g.Cc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.yh&&!p4(this.lc))break a;this.Eg||4!=b||7==c||(8==c||0>=d?this.g.me(3):this.g.me(2));p5(this);var e=this.lc.getStatus();this.Fj=e;var f=p4(this.lc);(this.re=200==e)?(4==b&&h5(this),this.u?(j5(this,b,f),g.yh&&this.re&&3==b&&(this.ca.da(this.i,"tick",this.uL),this.i.start())):g5(this,f),this.re&&!this.Eg&&(4==b?this.g.Xm(this):(this.re=
!1,c5(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.dg=3,e5(13)):(this.dg=0,e5(14)),h5(this),i5(this))}}catch(k){this.lc&&p4(this.lc)}finally{}};
g.h.uL=function(){var a=m4(this.lc),b=p4(this.lc);this.Mk<b.length&&(p5(this),j5(this,a,b),this.re&&4!=a&&c5(this))};
g.h.SK=function(a){o5((0,g.z)(this.RK,this,a),0)};
g.h.RK=function(a){this.Eg||(p5(this),g5(this,a),c5(this))};
g.h.Ny=function(a){o5((0,g.z)(this.QK,this,a),0)};
g.h.QK=function(a){this.Eg||(h5(this),this.re=a,this.g.Xm(this),this.g.me(4))};
g.h.cancel=function(){this.Eg=!0;h5(this)};
g.h.cL=function(){this.Ki=null;var a=(0,g.C)();0<=a-this.Rs?(2!=this.Nh&&this.g.me(3),h5(this),this.dg=2,e5(18),i5(this)):n5(this,this.Rs-a)};
g.h.getLastError=function(){return this.dg};g.h=t5.prototype;g.h.Gp=null;g.h.Bd=null;g.h.pn=!1;g.h.Pv=null;g.h.Hl=null;g.h.wq=null;g.h.Hp=null;g.h.Vd=null;g.h.uf=-1;g.h.Ej=null;g.h.Yi=null;g.h.connect=function(a){this.Hp=a;a=u5(this.g,null,this.Hp);e5(3);this.Pv=(0,g.C)();var b=this.g.D;null!=b?(this.Ej=b[0],(this.Yi=b[1])?(this.Vd=1,v5(this)):(this.Vd=2,x5(this))):(f4(a,"MODE","init"),this.Bd=new Z4(this,void 0,void 0,void 0),this.Bd.Mg=this.Gp,b5(this.Bd,a,!1,null,!0),this.Vd=0)};
g.h.aC=function(a){if(a)this.Vd=2,x5(this);else{e5(4);var b=this.g;b.Ee=b.Tf.uf;R5(b,9)}a&&this.me(2)};
g.h.cp=function(a){return this.g.cp(a)};
g.h.abort=function(){this.Bd&&(this.Bd.cancel(),this.Bd=null);this.uf=-1};
g.h.Ov=function(){return!1};
g.h.Hy=function(a,b){this.uf=a.Fj;if(0==this.Vd)if(b){try{var c=this.i.parse(b)}catch(d){c=this.g;c.Ee=this.uf;R5(c,2);return}this.Ej=c[0];this.Yi=c[1]}else c=this.g,c.Ee=this.uf,R5(c,2);else if(2==this.Vd)if(this.pn)e5(7),this.wq=(0,g.C)();else if("11111"==b){if(e5(6),this.pn=!0,this.Hl=(0,g.C)(),c=this.Hl-this.Pv,!g.Md||g.Dc(10)||500>c)this.uf=200,this.Bd.cancel(),e5(12),w5(this.g,this,!0)}else e5(8),this.Hl=this.wq=(0,g.C)(),this.pn=!1};
g.h.Xm=function(){this.uf=this.Bd.Fj;if(this.Bd.re)0==this.Vd?this.Yi?(this.Vd=1,v5(this)):(this.Vd=2,x5(this)):2==this.Vd&&((!g.Md||g.Dc(10)?!this.pn:200>this.wq-this.Hl)?(e5(11),w5(this.g,this,!1)):(e5(12),w5(this.g,this,!0)));else{0==this.Vd?e5(9):2==this.Vd&&e5(10);var a=this.g;this.Bd.getLastError();a.Ee=this.uf;R5(a,2)}};
g.h.Fk=function(){return this.g.Fk()};
g.h.isActive=function(){return this.g.isActive()};
g.h.me=function(a){this.g.me(a)};g.h=y5.prototype;g.h.lj=null;g.h.yd=null;g.h.Sb=null;g.h.Fp=null;g.h.Jl=null;g.h.ku=null;g.h.Sl=null;g.h.lk=0;g.h.aH=0;g.h.Tc=null;g.h.Yf=null;g.h.gf=null;g.h.Ig=null;g.h.Tf=null;g.h.Yn=null;g.h.Yh=-1;g.h.ww=-1;g.h.Ee=-1;g.h.Ih=0;g.h.Ch=0;g.h.Fg=8;var S5=new g.Qf;g.A(z5,g.sf);g.A(A5,g.sf);g.A(B5,g.sf);g.h=y5.prototype;g.h.connect=function(a,b,c,d,e){e5(0);this.Fp=b;this.lj=c||{};d&&g.Ba(e)&&(this.lj.OSID=d,this.lj.OAID=e);this.A?(o5((0,g.z)(this.Bu,this,a),100),H5(this)):this.Bu(a)};
g.h.Bu=function(a){this.Tf=new t5(this);this.Tf.Gp=null;this.Tf.i=this.u;this.Tf.connect(a)};
g.h.Ov=function(){return 0==this.g};
g.h.My=function(a){this.Yf=null;M5(this,a)};
g.h.Ly=function(){this.gf=null;this.Sb=new Z4(this,this.l,"rpc",this.B);this.Sb.Mg=null;this.Sb.Ip=0;var a=this.ku.clone();g.dn(a,"RID","rpc");g.dn(a,"SID",this.l);g.dn(a,"CI",this.Yn?"0":"1");g.dn(a,"AID",this.Yh);D5(this,a);if(!g.Md||g.Dc(10))g.dn(a,"TYPE","xmlhttp"),b5(this.Sb,a,!0,this.Sl,!1);else{g.dn(a,"TYPE","html");var b=this.Sb,c=!!this.Sl;b.Nh=3;b.cg=e4(a.clone());m5(b,c)}};
g.h.Hy=function(a,b){if(0!=this.g&&(this.Sb==a||this.yd==a))if(this.Ee=a.Fj,this.yd==a&&3==this.g)if(7<this.Fg){try{var c=this.u.parse(b)}catch(f){c=null}if(g.Ja(c)&&3==c.length)if(0==c[0])a:{if(!this.gf){if(this.Sb)if(this.Sb.si+3E3<this.yd.si)I5(this),this.Sb.cancel(),this.Sb=null;else break a;P5(this);e5(19)}}else this.ww=c[1],0<this.ww-this.Yh&&37500>c[2]&&this.Yn&&0==this.Ch&&!this.Ig&&(this.Ig=o5((0,g.z)(this.FH,this),6E3));else R5(this,11)}else b!=zqa.tN.g&&R5(this,11);else if(this.Sb==a&&
I5(this),!g.wb(b)){c=this.u.parse(b);g.Ja(c);for(var d=0;d<c.length;d++){var e=c[d];this.Yh=e[0];e=e[1];2==this.g?"c"==e[0]?(this.l=e[1],this.Sl=e[2],e=e[3],null!=e?this.Fg=e:this.Fg=6,this.g=3,this.Tc&&this.Tc.vu(),this.ku=u5(this,this.Fk()?this.Sl:null,this.Fp),N5(this)):"stop"==e[0]&&R5(this,7):3==this.g&&("stop"==e[0]?R5(this,7):"noop"!=e[0]&&this.Tc&&this.Tc.uu(e),this.Ch=0)}}};
g.h.FH=function(){null!=this.Ig&&(this.Ig=null,this.Sb.cancel(),this.Sb=null,P5(this),e5(20))};
g.h.Xm=function(a){if(this.Sb==a){I5(this);this.Sb=null;var b=2}else if(this.yd==a)this.yd=null,b=1;else return;this.Ee=a.Fj;if(0!=this.g)if(a.re)1==b?(b=(0,g.C)()-a.si,S5.dispatchEvent(new A5(S5,a.ih?a.ih.length:0,b,this.Ih)),G5(this),this.o.length=0):N5(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Ee)){if(d=1==b)this.yd||this.Yf||1==this.g||2<=this.Ih?d=!1:(this.Yf=o5((0,g.z)(this.My,this,a),O5(this,this.Ih)),this.Ih++,d=!0);d=!(d||2==b&&P5(this))}if(d)switch(c){case 1:R5(this,
5);break;case 4:R5(this,10);break;case 3:R5(this,6);break;case 7:R5(this,12);break;default:R5(this,2)}}};
g.h.rC=function(a){if(!g.$a(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.aM=function(a){a?e5(2):(e5(1),Q5(this,8))};
g.h.cp=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new o4;a.R=!1;return a};
g.h.isActive=function(){return!!this.Tc&&this.Tc.isActive(this)};
g.h.me=function(a){S5.dispatchEvent(new B5(S5,a))};
g.h.Fk=function(){return!(!g.Md||g.Dc(10))};
g.h=T5.prototype;g.h.vu=function(){};
g.h.uu=function(){};
g.h.tu=function(){};
g.h.Qo=function(){};
g.h.uv=function(){return{}};
g.h.isActive=function(){return!0};g.A(U5,g.G);g.h=U5.prototype;g.h.KK=function(){this.Vc=Math.min(3E5,2*this.Vc);this.l();this.i&&this.start()};
g.h.start=function(){var a=this.Vc+15E3*Math.random();g.no(this.g,a);this.i=(0,g.C)()+a};
g.h.stop=function(){this.g.stop();this.i=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Vc=5E3};g.A(V5,T5);g.h=V5.prototype;g.h.subscribe=function(a,b,c){return this.l.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.l.unsubscribe(a,b,c)};
g.h.Bf=function(a){return this.l.Ng(a)};
g.h.N=function(a,b){return this.l.N.apply(this.l,arguments)};
g.h.dispose=function(){this.ab||(this.ab=!0,g.qf(this.l),W5(this),g.qf(this.i),this.i=null)};
g.h.ea=function(){return this.ab};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.F="";this.i.stop();this.u=a||null;this.o=b||0;a=this.H+"/test";b=this.H+"/bind";var d=new y5(c?c.firstTestResults:null,c?c.secondTestResults:null,this.J),e=this.g;e&&(e.Tc=null);d.Tc=this;this.g=d;e?this.g.connect(a,b,this.A,e.l,e.Yh):c?this.g.connect(a,b,this.A,c.sessionId,c.arrayId):this.g.connect(a,b,this.A)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.ec(c,b);this.i.isActive()||2==(this.g?this.g.g:0)?this.B.push(c):X5(this)&&J5(this.g,c)};
g.h.vu=function(){this.i.reset();this.u=null;this.o=0;if(this.B.length){var a=this.B;this.B=[];for(var b=0,c=a.length;b<c;++b)J5(this.g,a[b])}this.N("handlerOpened")};
g.h.tu=function(a){var b=2==a&&401==this.g.Ee;4==a||b||this.i.start();this.N("handlerError",a)};
g.h.Qo=function(a){if(!this.i.isActive())this.N("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.B.push(d)}};
g.h.uv=function(){var a={v:2};this.F&&(a.gsessionid=this.F);0!=this.o&&(a.ui=""+this.o);0!=this.D&&(a.ui=""+this.D);this.u&&g.ec(a,this.u);return a};
g.h.uu=function(a){"S"==a[0]?this.F=a[1]:"gracefulReconnect"==a[0]?(this.i.start(),F5(this.g)):this.N("handlerMessage",new Rpa(a[0],a[1]))};
g.h.tM=function(){this.i.isActive();var a=this.g,b=0;a.Sb&&b++;a.yd&&b++;0!=b||this.connect(this.u,this.o)};Y5.prototype.o=function(a,b,c,d){b?a(d):a({text:c.responseText})};
Y5.prototype.l=function(a,b){a(Error("Request error: "+b.status))};
Y5.prototype.u=function(a){a(Error("request timed out"))};var Xpa=(0,g.C)(),c6=null,g6=Array(50),f6=-1,h6=!1;g.A(i6,g.O);i6.prototype.Gd=function(){return this.g};
i6.prototype.contains=function(a){return!!D4(this.g,a)};
i6.prototype.get=function(a){return a?E4(this.g,a):null};
i6.prototype.info=function(a){e6(this.B,a)};g.A(k6,g.O);var p8=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=k6.prototype;g.h.start=function(){!this.g&&isNaN(this.za)&&this.QA()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);isNaN(this.za)||(g.Rp(this.za),this.za=NaN)};
g.h.T=function(){this.stop();k6.Ha.T.call(this)};
g.h.QA=function(){this.za=NaN;this.g=g.Eq(Z5(this.A,"/pairing/get_screen"),{method:"POST",qb:{pairing_code:this.u},timeout:5E3,onSuccess:(0,g.z)(this.vM,this),onError:(0,g.z)(this.uM,this),md:(0,g.z)(this.wM,this)})};
g.h.vM=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.l;c.name=this.o;this.N("pairingComplete",new w4(c))};
g.h.uM=function(a){this.g=null;a.status&&404==a.status?this.i>=p8.length?this.N("pairingFailed",Error("DIAL polling timed out")):(a=p8[this.i],this.za=g.Pp((0,g.z)(this.QA,this),a),this.i++):this.N("pairingFailed",Error("Server error "+a.status))};
g.h.wM=function(){this.g=null;this.N("pairingFailed",Error("Server not responding"))};g.A(m6,i6);g.h=m6.prototype;g.h.start=function(){l6(this)&&this.N("screenChange");!g.gt("yt-remote-lounge-token-expiration")&&n6(this);g.Rp(this.i);this.i=g.Pp((0,g.z)(this.start,this),1E4)};
g.h.add=function(a,b){l6(this);j6(this,a);o6(this,!1);this.N("screenChange");b(a);a.token||n6(this)};
g.h.remove=function(a,b){var c=l6(this);Zpa(this,a)&&(o6(this,!1),c=!0);b(a);c&&this.N("screenChange")};
g.h.Un=function(a,b,c,d){var e=l6(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,o6(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.N("screenChange")};
g.h.T=function(){g.Rp(this.i);m6.Ha.T.call(this)};
g.h.aD=function(a){l6(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}o6(this,!b);b&&e6(this.B,"Missed "+b+" lounge tokens.")};
g.h.ZC=function(a){e6(this.B,"Requesting lounge tokens failed: "+a)};g.A(q6,g.O);g.h=q6.prototype;g.h.start=function(){var a=parseInt(g.gt("yt-remote-fast-check-period")||"0",10);(this.o=(0,g.C)()-144E5<a?0:a)?t6(this):(this.o=(0,g.C)()+3E5,g.ft("yt-remote-fast-check-period",this.o),this.Tr())};
g.h.isEmpty=function(){return g.Xb(this.g)};
g.h.update=function(){p6("Updating availability on schedule.");var a=this.A(),b=g.Lb(this.g,function(c,d){return c&&!!E4(a,d)},this);
s6(this,b)};
g.h.T=function(){g.Rp(this.l);this.l=NaN;this.i&&(this.i.abort(),this.i=null);q6.Ha.T.call(this)};
g.h.Tr=function(){g.Rp(this.l);this.l=NaN;this.i&&this.i.abort();var a=u6(this);if(r4(a)){var b=Z5(this.u,"/pairing/get_screen_availability");this.i=$5(this.u,b,{lounge_token:g.Rb(a).join(",")},(0,g.z)(this.oK,this,a),(0,g.z)(this.nK,this))}else s6(this,{}),t6(this)};
g.h.oK=function(a,b){this.i=null;var c=g.Rb(u6(this));if(g.rb(c,g.Rb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;s6(this,d);t6(this)}else this.Kb("Changing Screen set during request."),this.Tr()};
g.h.nK=function(a){this.Kb("Screen availability failed: "+a);this.i=null;t6(this)};
g.h.Kb=function(a){e6("OnlineScreenService",a)};g.A(v6,i6);g.h=v6.prototype;g.h.start=function(){this.l.start();this.i.start();this.g.length&&(this.N("screenChange"),this.i.isEmpty()||this.N("onlineScreenChange"))};
g.h.add=function(a,b,c){this.l.add(a,b,c)};
g.h.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.h.Un=function(a,b,c,d){this.l.contains(a)?this.l.Un(a,b,c,d):(a="Updating name of unknown screen: "+a.name,e6(this.B,a),d(Error(a)))};
g.h.Gd=function(a){return a?this.g:g.fb(this.g,(0,g.Yd)(this.o,function(b){return!this.contains(b)},this))};
g.h.RA=function(){return(0,g.Yd)(this.Gd(!0),function(a){return!!this.i.g[a.id]},this)};
g.h.SA=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new k6(this.A,a,b,c);f.subscribe("pairingComplete",(0,g.z)(function(k){g.qf(f);d(w6(this,k))},this));
f.subscribe("pairingFailed",function(k){g.qf(f);e(k)});
f.start();return(0,g.z)(f.stop,f)};
g.h.yM=function(a,b,c,d){g.Eq(Z5(this.A,"/pairing/get_screen"),{method:"POST",qb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.z)(function(e,f){var k=new w4(f.screen||{});if(!k.name||y6(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);y6(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(w6(this,k))},this),
onError:(0,g.z)(function(e){d(Error("pairing request failed: "+e.status))},this),
md:(0,g.z)(function(){d(Error("pairing request timed out."))},this)})};
g.h.T=function(){g.qf(this.l);g.qf(this.i);v6.Ha.T.call(this)};
g.h.jD=function(){z6(this);this.N("screenChange");this.i.update()};
v6.prototype.dispose=v6.prototype.dispose;g.A(B6,g.O);g.h=B6.prototype;g.h.Ym=function(a){this.l=a;this.N("sessionScreen",this.l)};
g.h.Jd=function(a){this.ea()||(a&&C6(this,""+a),this.l=null,this.N("sessionScreen",null))};
g.h.info=function(a){e6(this.P,a)};
g.h.UA=function(){return null};
g.h.hs=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.z)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.z)(function(){C6(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.T=function(){this.hs("");B6.Ha.T.call(this)};g.A(E6,B6);g.h=E6.prototype;g.h.gs=function(a){if(this.g){if(this.g==a)return;C6(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.A);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u)}this.g=a;this.g.addUpdateListener(this.A);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.u);cqa(this)};
g.h.ai=function(a){this.info("launchWithParams no-op for Cast: "+g.Hg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.z)(function(){this.Jd()},this),(0,g.z)(function(){this.Jd(Error("Failed to stop receiver app."))},this)):this.Jd(Error("Stopping cast device witout session."))};
g.h.hs=g.Fa;g.h.T=function(){this.info("disposeInternal");g.Rp(this.o);this.o=0;this.g&&(this.g.removeUpdateListener(this.A),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u));this.g=null;E6.Ha.T.call(this)};
g.h.nL=function(a,b){if(!this.ea())if(b){var c=s4(b);if(g.Na(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Hg(c));switch(d){case "mdxSessionStatus":D6(this,c.screenId);break;default:C6(this,"Unknown youtube message: "+d)}}else C6(this,"Unable to parse message.")}else C6(this,"No data in message.")};
g.h.Hv=function(a,b,c,d){x6(this.F,this.i.label,a,this.i.friendlyName,(0,g.z)(function(e){e?b(e):0<=d?(C6(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Pp((0,g.z)(this.Hv,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.UA=function(){return this.g};
g.h.zM=function(a){this.ea()||a||(C6(this,"Cast session died."),this.Jd())};g.A(F6,B6);g.h=F6.prototype;g.h.gs=function(a){this.o=a;this.o.addUpdateListener(this.J)};
g.h.ai=function(a){this.u=a;this.B()};
g.h.stop=function(){this.g();this.g=g.Fa;g.Rp(this.A);this.o?this.o.stop((0,g.z)(this.Jd,this,null),(0,g.z)(this.Jd,this,"Failed to stop DIAL device.")):this.Jd()};
g.h.T=function(){this.g();this.g=g.Fa;g.Rp(this.A);this.o&&this.o.removeUpdateListener(this.J);this.o=null;F6.Ha.T.call(this)};
g.h.CM=function(a){this.ea()||a||(C6(this,"DIAL session died."),this.g(),this.g=g.Fa,this.Jd())};
g.h.Vp=function(a){this.H=C4();if(this.u){var b=new chrome.cast.DialLaunchResponse(!0,H6(this));a(b);G6(this)}else this.B=(0,g.z)(function(){g.Rp(this.A);this.B=g.Fa;this.A=NaN;var c=new chrome.cast.DialLaunchResponse(!0,H6(this));a(c);G6(this)},this),this.A=g.Pp((0,g.z)(function(){this.B()},this),100)};
g.h.ED=function(a,b,c){x6(this.F,this.D.receiver.label,a,this.i.friendlyName,(0,g.z)(function(d){d&&d.token?(this.Ym(d),b(new chrome.cast.DialLaunchResponse(!1))):this.Vp(b,c)},this),(0,g.z)(function(d){C6(this,"Failed to get DIAL screen: "+d);
this.Vp(b,c)},this))};g.A(I6,B6);I6.prototype.stop=function(){this.Jd()};
I6.prototype.gs=g.Fa;I6.prototype.ai=function(){g.Rp(this.g);this.g=NaN;var a=E4(this.F.Gd(),this.i.label);a?this.Ym(a):this.Jd(Error("No such screen"))};
I6.prototype.T=function(){g.Rp(this.g);this.g=NaN;I6.Ha.T.call(this)};g.A(J6,g.O);g.h=J6.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.B);this.D||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new chrome.cast.ApiConfig(c,(0,g.z)(this.Jy,this),(0,g.z)(this.XJ,this),d,e);c.customDialLaunchCallback=(0,g.z)(this.fI,this);chrome.cast.initialize(c,(0,g.z)(function(){this.ea()||
(chrome.cast.addReceiverActionListener(this.o),Upa(),this.i.subscribe("onlineScreenChange",(0,g.z)(this.TA,this)),this.l=O6(this),chrome.cast.setCustomReceivers(this.l,g.Fa,(0,g.z)(function(f){this.Kb("Failed to set initial custom receivers: "+g.Hg(f))},this)),this.N("yt-remote-cast2-availability-change",M6(this)),b(!0))},this),(0,g.z)(function(f){this.Kb("Failed to initialize API: "+g.Hg(f));
b(!1)},this))};
g.h.PL=function(a,b){L6("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.l;if(!a||c&&c.id!=a)L6("Unsetting old screen status: "+this.g.i.friendlyName),N6(this,null)}if(a&&b){if(!this.g){c=E4(this.i.Gd(),a);if(!c){L6("setConnectedScreenStatus: Unknown screen.");return}var d=K6(this,c);d||(L6("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.l.push(d),chrome.cast.setCustomReceivers(this.l,
g.Fa,(0,g.z)(function(e){this.Kb("Failed to set initial custom receivers: "+g.Hg(e))},this)));
L6("setConnectedScreenStatus: new active receiver: "+d.friendlyName);N6(this,new I6(this.i,d),!0)}this.g.hs(b)}else L6("setConnectedScreenStatus: no screen.")};
g.h.QL=function(a){this.ea()?this.Kb("Setting connection data on disposed cast v2"):this.g?this.g.ai(a):this.Kb("Setting connection data without a session")};
g.h.BM=function(){this.ea()?this.Kb("Stopping session on disposed cast v2"):this.g?(this.g.stop(),N6(this,null)):L6("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.z)(this.Jy,this),(0,g.z)(this.tK,this))};
g.h.T=function(){this.i.unsubscribe("onlineScreenChange",(0,g.z)(this.TA,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.o);g.cb(g.x("yt.mdx.remote.debug.handlers_")||[],a6);g.qf(this.g);J6.Ha.T.call(this)};
g.h.Kb=function(a){e6("Controller",a)};
g.h.Ky=function(a,b){this.g==a&&(b||N6(this,null),this.N("yt-remote-cast2-session-change",b))};
g.h.TJ=function(a,b){if(!this.ea())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),L6("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.i.label!=a.label)L6("onReceiverAction_: Stopping active receiver: "+this.g.i.friendlyName),this.g.stop();else{L6("onReceiverAction_: Casting to active receiver.");this.g.l&&this.N("yt-remote-cast2-session-change",this.g.l);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:N6(this,
new I6(this.i,a));break;case chrome.cast.ReceiverType.DIAL:N6(this,new F6(this.i,a,this.A));break;case chrome.cast.ReceiverType.CAST:N6(this,new E6(this.i,a));break;default:this.Kb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.g&&this.g.i.label==a.label?this.g.stop():this.Kb("Stopping receiver w/o session: "+a.friendlyName)}else this.Kb("onReceiverAction_ called without receiver.")};
g.h.fI=function(a){if(this.ea())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Kb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.i:null;if(!c||c.label!=b.label)return this.Kb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.g.l)return L6("Reselecting dial screen."),
this.N("yt-remote-cast2-session-change",this.g.l),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Kb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);N6(this,new F6(this.i,b,this.A))}b=this.g;b.D=a;return b.D.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.z)(b.ED,b,(b.D.extraData||{}).screenId||null)):new Promise((0,g.z)(b.Vp,b))};
g.h.Jy=function(a){if(!this.ea()){L6("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==chrome.cast.ReceiverType.CAST)L6("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),N6(this,new E6(this.i,b),!0);else{this.Kb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.i,d=E4(this.i.Gd(),c.label);d&&x4(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(L6("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.qf(this.g),this.g=new E6(this.i,b),this.g.subscribe("sessionScreen",(0,g.z)(this.Ky,this,this.g)),this.g.ai(null));this.g.gs(a)}}};
g.h.AM=function(){return this.g?this.g.UA():null};
g.h.tK=function(a){this.ea()||(this.Kb("Failed to estabilish a session: "+g.Hg(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&N6(this,null))};
g.h.XJ=function(a){L6("Receiver availability updated: "+a);if(!this.ea()){var b=M6(this);this.u=a==chrome.cast.ReceiverAvailability.AVAILABLE;M6(this)!=b&&this.N("yt-remote-cast2-availability-change",M6(this))}};
g.h.TA=function(){this.ea()||(this.l=O6(this),L6("Updating custom receivers: "+g.Hg(this.l)),chrome.cast.setCustomReceivers(this.l,g.Fa,(0,g.z)(function(){this.Kb("Failed to set custom receivers.")},this)),this.N("yt-remote-cast2-availability-change",M6(this)))};
J6.prototype.setLaunchParams=J6.prototype.QL;J6.prototype.setConnectedScreenStatus=J6.prototype.PL;J6.prototype.stopSession=J6.prototype.BM;J6.prototype.getCastSession=J6.prototype.AM;J6.prototype.requestSession=J6.prototype.requestSession;J6.prototype.init=J6.prototype.init;J6.prototype.dispose=J6.prototype.dispose;var X6=[];e7.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";f7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.g=a.trackData,this.Ge=a.hasPrevious,this.hasNext=a.hasNext,this.B=a.playerTime,this.A=a.playerTimeAt,this.o=a.seekableStart,this.i=a.seekableEnd,this.D=a.duration,this.F=a.loadedTime,this.l=a.liveIngestionTime,this.u=
!isNaN(this.l))};
e7.prototype.isAdPlaying=function(){return 1081==this.playerState};
e7.prototype.getDuration=function(){return this.u?this.D+g7(this):this.D};
e7.prototype.clone=function(){return new e7(k7(this))};g.A(n7,g.O);g.h=n7.prototype;g.h.play=function(){1==this.g?(this.i?this.i.play(null,g.Fa,v7(this,"play")):t7(this,"play"),s7(this,1,i7(o7(this))),this.N("remotePlayerChange")):q7(this,this.play)};
g.h.pause=function(){1==this.g?(this.i?this.i.pause(null,g.Fa,v7(this,"pause")):t7(this,"pause"),s7(this,2,i7(o7(this))),this.N("remotePlayerChange")):q7(this,this.pause)};
g.h.seekTo=function(a){if(1==this.g){if(this.i){var b=o7(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Fa,v7(this,"seekTo",{newTime:a}))}else t7(this,"seekTo",{newTime:a});s7(this,3,a);this.N("remotePlayerChange")}else q7(this,g.Qa(this.seekTo,a))};
g.h.stop=function(){if(1==this.g){this.i?this.i.stop(null,g.Fa,v7(this,"stopVideo")):t7(this,"stopVideo");var a=o7(this);a.index=-1;a.videoId="";f7(a);r7(this,a);this.N("remotePlayerChange")}else q7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=o7(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.z)(function(){e6("CP","set receiver volume: "+d)},this),(0,g.z)(function(){this.Kb("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.z)(function(){e6("CP","set receiver muted: "+b)},this),(0,g.z)(function(){this.Kb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);t7(this,"setVolume",e)}c.muted=b;c.volume=a;r7(this,c)}else q7(this,g.Qa(this.setVolume,a,b))};
g.h.Sz=function(a,b){if(1==this.g){var c=o7(this),d={videoId:a};b&&(c.g={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Hg(b.style),g.ec(d,c.g));t7(this,"setSubtitlesTrack",d);r7(this,c)}else q7(this,g.Qa(this.Sz,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.g){var c=b.getLanguageInfo().getId();t7(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=o7(this);d.audioTrackId=c;r7(this,d)}else q7(this,g.Qa(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=o7(this);c=c||0;var m={videoId:a,currentIndex:c};j7(l,a,c);g.Ba(b)&&(h7(l,b),m.currentTime=b);g.Ba(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Hg(k));t7(this,"setPlaylist",m);d||r7(this,l)};
g.h.gn=function(a,b){if(1==this.g){if(a&&b){var c=o7(this);j7(c,a,b);r7(this,c)}t7(this,"previous")}else q7(this,g.Qa(this.gn,a,b))};
g.h.nextVideo=function(a,b){if(1==this.g){if(a&&b){var c=o7(this);j7(c,a,b);r7(this,c)}t7(this,"next")}else q7(this,g.Qa(this.nextVideo,a,b))};
g.h.Tu=function(){1==this.g?t7(this,"dismissAutoplay"):q7(this,this.Tu)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.N("proxyStateChange",a,this.g)}n7.Ha.dispose.call(this)};
g.h.T=function(){p7(this);this.o=null;this.u.clear();m7(this,null);n7.Ha.T.call(this)};
g.h.Us=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.N("proxyStateChange",b,a);if(1==a)for(;!this.u.isEmpty();)b=a=this.u,0==b.g.length&&(b.g=b.i,b.g.reverse(),b.i=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.QJ=function(a,b){this.N(a,b)};
g.h.LH=function(a){if(!a)this.mk(null),m7(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=o7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)e6("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,r7(this,b)}};
g.h.mk=function(a){e6("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.D);if(this.i=a)this.i.addUpdateListener(this.D),u7(this),this.N("remotePlayerChange")};
g.h.KH=function(a){a?(u7(this),this.N("remotePlayerChange")):this.mk(null)};
g.h.Ds=function(){t7(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.XH=function(){var a=a7();a&&m7(this,a)};
g.h.Kb=function(a){e6("CP",a)};g.A(w7,g.O);g.h=w7.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.Ba(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.Ba(k)&&(l.currentIndex=k);c&&(this.Pa.listId=c);this.Pa.videoId=d;this.Pa.index=k||0;this.Pa.state=3;h7(this.Pa,m);this.o="UNSUPPORTED";x7("Connecting with setPlaylist and params: "+g.Hg(l));this.g.connect({method:"setPlaylist",
params:g.Hg(l)},a,K4())}else x7("Connecting without params"),this.g.connect({},a,K4());jqa(this)};
g.h.dispose=function(){this.ea()||(this.N("beforeDispose"),y7(this,3));w7.Ha.dispose.call(this)};
g.h.T=function(){z7(this);B7(this);A7(this);g.Rp(this.F);this.F=NaN;g.Rp(this.H);this.H=NaN;this.l=null;g.Er(this.O);this.O.length=0;this.g.dispose();w7.Ha.T.call(this);this.o=this.B=this.i=this.Pa=this.g=null};
g.h.TC=function(){this.A(2)};
g.h.PH=function(){x7("Channel opened");this.M&&(this.M=!1,A7(this),this.P=g.Pp((0,g.z)(function(){x7("Timing out waiting for a screen.");this.A(1)},this),15E3));
Lpa(Spa(this.g),this.V)};
g.h.MH=function(){x7("Channel closed");isNaN(this.u)?N4(!0):N4();this.dispose()};
g.h.NH=function(a){N4();isNaN(this.D())?(x7("Channel error: "+a+" without reconnection"),this.dispose()):(this.M=!0,x7("Channel error: "+a+" with reconnection in "+this.D()+" ms"),y7(this,2))};
g.h.OH=function(a){a.params?x7("Received: action="+a.action+", params="+g.Hg(a.params)):x7("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=s4(a.params.devices);this.i=(0,g.F)(a,function(c){return new v4(c)});
a=!!g.Xa(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
E7(this,a);break;case "loungeScreenDisconnected":g.db(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
E7(this,!1);break;case "remoteConnected":var b=new v4(s4(a.params.device));g.Xa(this.i,function(c){return b?c.id==b.id:!1})||zpa(this.i,b);
break;case "remoteDisconnected":b=new v4(s4(a.params.device));g.db(this.i,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":F7(this,a);break;case "nowPlaying":mqa(this,a);break;case "onStateChange":G7(this,a);break;case "onAdStateChange":nqa(this,a);break;case "onVolumeChanged":oqa(this,a);break;case "onSubtitlesTrackChanged":lqa(this,a);break;case "nowAutoplaying":pqa(this,a);break;case "autoplayDismissed":this.N("autoplayDismissed");break;case "autoplayUpNext":this.B=a.params.videoId||null;this.N("autoplayUpNext",this.B);break;case "onAutoplayModeChanged":this.o=
a.params.autoplayMode;this.N("autoplayModeChange",this.o);"DISABLED"==this.o&&this.N("autoplayDismissed");break;case "onHasPreviousNextChanged":qqa(this,a);break;case "requestAssistedSignIn":this.N("assistedSignInRequested",a.params.authCode);break;default:x7("Unrecognized action: "+a.action)}};
g.h.EL=function(){if(this.l){var a=this.l;this.l=null;this.Pa.videoId!=a&&C7(this,"getNowPlaying")}};
w7.prototype.subscribe=w7.prototype.subscribe;w7.prototype.unsubscribeByKey=w7.prototype.Bf;w7.prototype.aa=function(){var a=3;this.ea()||(a=0,isNaN(this.D())?X5(this.g)&&isNaN(this.u)&&(a=1):a=2);return a};
w7.prototype.getProxyState=w7.prototype.aa;w7.prototype.A=function(a){x7("Disconnecting with "+a);z7(this);this.N("beforeDisconnect",a);1==a&&N4();W5(this.g,a);this.dispose()};
w7.prototype.disconnect=w7.prototype.A;w7.prototype.X=function(){var a=this.Pa;this.l&&(a=this.Pa.clone(),j7(a,this.l,a.index));return k7(a)};
w7.prototype.getPlayerContextData=w7.prototype.X;
w7.prototype.ka=function(a){var b=new e7(a);b.videoId&&b.videoId!=this.Pa.videoId&&(this.l=b.videoId,g.Rp(this.F),this.F=g.Pp((0,g.z)(this.EL,this),5E3));var c=[];this.Pa.listId==b.listId&&this.Pa.videoId==b.videoId&&this.Pa.index==b.index||c.push("remoteQueueChange");this.Pa.playerState==b.playerState&&this.Pa.volume==b.volume&&this.Pa.muted==b.muted&&i7(this.Pa)==i7(b)&&g.Hg(this.Pa.g)==g.Hg(b.g)||c.push("remotePlayerChange");this.Pa.reset(a);(0,g.B)(c,function(d){this.N(d)},this)};
w7.prototype.setPlayerContextData=w7.prototype.ka;w7.prototype.R=function(){var a=this.g.A.id,b=g.Xa(this.i,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
w7.prototype.getOtherConnectedRemoteId=w7.prototype.R;w7.prototype.D=function(){var a=this.g;return a.i.isActive()?a.i.i-(0,g.C)():NaN};
w7.prototype.getReconnectTimeout=w7.prototype.D;w7.prototype.ba=function(){return this.o||"UNSUPPORTED"};
w7.prototype.getAutoplayMode=w7.prototype.ba;w7.prototype.Y=function(){return this.B||""};
w7.prototype.getAutoplayVideoId=w7.prototype.Y;w7.prototype.ua=function(){if(!isNaN(this.D())){var a=this.g.i;g.oo(a.g);a.start()}};
w7.prototype.reconnect=w7.prototype.ua;w7.prototype.ga=function(a,b){C7(this,a,b);D7(this)};
w7.prototype.sendMessage=w7.prototype.ga;g.A(H7,i6);g.h=H7.prototype;g.h.Gd=function(a){return this.Fc.$_gs(a)};
g.h.contains=function(a){return!!this.Fc.$_c(a)};
g.h.get=function(a){return this.Fc.$_g(a)};
g.h.start=function(){this.Fc.$_st()};
g.h.add=function(a,b,c){this.Fc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Fc.$_r(a,b,c)};
g.h.Un=function(a,b,c,d){this.Fc.$_un(a,b,c,d)};
g.h.T=function(){for(var a=0,b=this.i.length;a<b;++a)this.Fc.$_ubk(this.i[a]);this.i.length=0;this.Fc=null;H7.Ha.T.call(this)};
g.h.xM=function(){this.N("screenChange")};
g.h.uJ=function(){this.N("onlineScreenChange")};
v6.prototype.$_st=v6.prototype.start;v6.prototype.$_gspc=v6.prototype.yM;v6.prototype.$_gsppc=v6.prototype.SA;v6.prototype.$_c=v6.prototype.contains;v6.prototype.$_g=v6.prototype.get;v6.prototype.$_a=v6.prototype.add;v6.prototype.$_un=v6.prototype.Un;v6.prototype.$_r=v6.prototype.remove;v6.prototype.$_gs=v6.prototype.Gd;v6.prototype.$_gos=v6.prototype.RA;v6.prototype.$_s=v6.prototype.subscribe;v6.prototype.$_ubk=v6.prototype.Bf;var I7=null,J7=null,Z7=null,N7=[];g.t(b8,g.G);g.h=b8.prototype;
g.h.T=function(){g.G.prototype.T.call(this);this.o.stop();this.A.stop();this.J.stop();this.M();this.g.unsubscribe("proxyStateChange",this.Gy,this);this.g.unsubscribe("remotePlayerChange",this.pk,this);this.g.unsubscribe("remoteQueueChange",this.Zm,this);this.g.unsubscribe("autoplayUpNext",this.hy,this);this.g.unsubscribe("previousNextChange",this.Dy,this);this.g.unsubscribe("nowAutoplaying",this.zy,this);this.g.unsubscribe("autoplayDismissed",this.gy,this);this.g=this.u=null};
g.h.gx=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(f8(this)){if(!o7(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==o7(this.g).playerState?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.H.Bj(c[0],c[1]);break;case "control_subtitles_set_track":g8(this,c[0]);break;case "control_set_audio_track":c=c[0],f8(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.i.getCurrentTime();h8(this,0==c?void 0:c);break;case "control_seek":h8(this,c[0]);break;case "control_subtitles_set_track":g8(this,c[0]);break;case "control_set_audio_track":c=c[0],f8(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,c)}};
g.h.JH=function(a){this.J.PC(a)};
g.h.iM=function(a){this.gx("control_subtitles_set_track",g.Xb(a)?null:a)};
g.h.eA=function(){var a=this.i.getOption("captions","track");g.Xb(a)||g8(this,a)};
g.h.uy=function(a){if(f8(this)){this.g.unsubscribe("remotePlayerChange",this.pk,this);var b=Math.round(a.volume);a=!!a.muted;var c=o7(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.P.start();this.g.subscribe("remotePlayerChange",this.pk,this)}};
g.h.KI=function(){g.Xb(this.B)||i8(this,this.B);this.D=!1};
g.h.Gy=function(a,b){this.A.stop();2==b&&this.dA()};
g.h.pk=function(){if(f8(this)){this.o.stop();var a=o7(this.g);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.u.om=1;break;case 1082:case 1083:this.u.om=0;break;default:this.u.om=-1}switch(a.playerState){case 1081:case 1:d8(this,new g.EC(8));this.cA();break;case 1085:case 3:d8(this,new g.EC(9));break;case 1083:case 0:d8(this,new g.EC(2));this.H.stop();c8(this,this.i.getVideoData().lengthSeconds);break;case 1084:d8(this,new g.EC(4));break;case 2:d8(this,new g.EC(4));c8(this,i7(a));
break;case -1:d8(this,new g.EC(64));break;case -1E3:d8(this,new g.EC(128,{errorCode:"mdx.remoteerror",message:"This video is not available for remote playback."}))}a=o7(this.g).g;var b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.B=a,i8(this,a));a=o7(this.g);-1==a.volume||Math.round(this.i.getVolume())==a.volume&&this.i.isMuted()==a.muted||this.P.isActive()||this.DA()}else e8(this)};
g.h.Dy=function(){this.i.N("mdxpreviousnextchange")};
g.h.Zm=function(){f8(this)||e8(this)};
g.h.ZB=function(){this.g.Tu()};
g.h.hy=function(a){a&&(a=g.Eq("/watch_queue_ajax",{method:"GET",Ac:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.z)(this.VK,this)}))&&(this.M=(0,g.z)(a.abort,a))};
g.h.VK=function(a,b){var c=new g.KA(g.V(this.i),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.i.N("mdxautoplayupnext",c)};
g.h.zy=function(a){isNaN(a)||this.i.N("mdxnowautoplaying",a)};
g.h.gy=function(){this.i.N("mdxautoplaycanceled")};
g.h.oF=function(a,b){-1==o7(this.g).playerState?h8(this,a):b&&this.g.seekTo(a)};
g.h.DA=function(){if(f8(this)){var a=o7(this.g);this.l.Oa(this.O);a.muted?this.i.mute():this.i.unMute();this.i.setVolume(a.volume);this.O=this.l.K(this.i,"onVolumeChange",this.uy)}};
g.h.cA=function(){this.o.stop();if(!this.g.ea()){var a=o7(this.g);1==a.playerState&&d8(this,new g.EC(8));c8(this,i7(a));this.o.start()}};
g.h.dA=function(){this.A.stop();this.o.stop();var a=this.g.o.getReconnectTimeout();2==this.g.g&&!isNaN(a)&&this.A.start()};g.t(l8,g.T);l8.prototype.u=function(a){k8(this,a.state)};g.t(m8,g.dT);m8.prototype.J=function(){var a=this.l.getOption("remote","receivers");a&&1<a.length&&!this.l.getOption("remote","quickCast")?(this.F=g.tb(a,this.A,this),g.eT(this,(0,g.F)(a,this.A)),a=this.l.getOption("remote","currentReceiver"),this.le(this.A(a)),this.enable(!0)):this.enable(!1)};
m8.prototype.A=function(a){return a.key};
m8.prototype.ke=function(a){return"cast-selector-receiver"==a?"Cast...":this.F[a].name};
m8.prototype.Ic=function(a){g.dT.prototype.Ic.call(this,a);this.l.setOption("remote","currentReceiver",this.F[a]);this.o.ib()};g.t(n8,g.ZJ);g.h=n8.prototype;g.h.create=function(){vqa(g.Cy(g.V(this.player)));this.u.push(g.Wp("yt-remote-before-disconnect",this.GH,this));this.u.push(g.Wp("yt-remote-connection-change",this.YJ,this));this.u.push(g.Wp("yt-remote-receiver-availability-change",this.Ey,this));this.u.push(g.Wp("yt-remote-auto-connect",this.WJ,this));this.u.push(g.Wp("yt-remote-receiver-resumed",this.VJ,this));this.Ey()};
g.h.load=function(){this.player.cancelPlayback();g.ZJ.prototype.load.call(this);this.o=new b8(this,this.player,this.g);var a=(a=a8())?a.currentTime:0;var b=Y7()?new n7(T7(),void 0):null;0==a&&b&&(a=i7(o7(b)));0!=a&&this.pd(a);j8(this,this.ak,this.ak);g.hX(this.player.app,6)};
g.h.unload=function(){this.player.N("mdxautoplaycanceled");this.l=this.i;g.rf(this.o,this.g);this.g=this.o=null;g.ZJ.prototype.unload.call(this);g.hX(this.player.app,5)};
g.h.T=function(){g.Xp(this.u);g.ZJ.prototype.T.call(this)};
g.h.Re=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.o.gx.apply(this.o,[a].concat(g.ea(c)))};
g.h.getAdState=function(){return this.om};
g.h.LC=function(){return this.loaded?this.o.suggestion:null};
g.h.Ge=function(){return this.g?o7(this.g).Ge:!1};
g.h.hasNext=function(){return this.g?o7(this.g).hasNext:!1};
g.h.pd=function(a,b){this.D=a||0;this.player.N("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.D};
g.h.getProgressState=function(){var a=o7(this.g),b=this.player.getVideoData();return{allowSeeking:g.Q(g.V(this.player).experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.Yb():!a.isAdPlaying()&&this.player.Yb(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.l+g7(a):a.l,isAtLiveHead:1>=(a.u?a.i+g7(a):a.i)-this.getCurrentTime(),loaded:a.F,seekableEnd:a.u?a.i+g7(a):a.i,seekableStart:0<a.o?a.o+
g7(a):a.o}};
g.h.nextVideo=function(){this.g&&this.g.nextVideo()};
g.h.gn=function(){this.g&&this.g.gn()};
g.h.GH=function(a){1==a&&(this.B=this.g?o7(this.g):null)};
g.h.YJ=function(){var a=Y7()?new n7(T7(),void 0):null;if(a){var b=this.l;this.loaded&&this.unload();this.g=a;this.B=null;b.key!=this.i.key&&(this.l=b,this.load())}else g.qf(this.g),this.g=null,this.loaded&&(this.unload(),(a=this.B)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,i7(a)));this.player.N("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.Ey=function(){this.A=[this.i].concat(wqa());var a=U7()||this.i;o8(this,a);this.player.ma("onMdxReceiversChange")};
g.h.WJ=function(){var a=U7();o8(this,a)};
g.h.VJ=function(){this.l=U7()};
g.h.Vb=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.A;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?c7():o8(this,b)),this.loaded?this.l:this.i;case "quickCast":return 2==this.A.length&&"cast-selector-receiver"==this.A[1].key?(b&&c7(),!0):!1}};
g.h.Ds=function(){this.g.Ds()};
g.h.Nb=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.uU.remote=n8;})(_yt_player);
